=== renil28/SecurityXMLProgs/Security.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Security">
	<xs:complexType>
	<xs:sequence>
		<xs:element name="SecurityAgency" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="AgencyName" type="xs:string"></xs:element>
				<xs:element name="AgencyID" type="xs:integer"></xs:element>	
			</xs:sequence>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="SecurityPersonnel" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"></xs:element>
				<xs:element name="Age" type="age"></xs:element>
				<xs:element name="Salary" type="SecuritySal"></xs:element>
				<xs:element name="YearsOfExperience" type="xs:integer"></xs:element>
			</xs:sequence>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="SecurityEquipment" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="EquipmentName" type="xs:string"></xs:element>
				<xs:element name="EquipmentType" type="xs:string"></xs:element>
				<xs:element name="EquipmentID" type="xs:integer"></xs:element>
			</xs:sequence>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="BaggageScanning" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="BaggageName" type="xs:string"></xs:element>
				<xs:element name="BaggageID" type="xs:integer"></xs:element>
			</xs:sequence>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="SecurityScreening" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="GateFloorNumber" type="floor"></xs:element>
				<xs:element name="GateID" type="xs:integer"></xs:element>
			</xs:sequence>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="CCTVCameras" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="CameraFloor" type="floor"></xs:element>
				<xs:element name="CameraNumber" type="xs:integer"></xs:element>
			</xs:sequence>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="MallAdmin" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="AdminName" type="xs:string"></xs:element>
				<xs:element name="AdminID" type="xs:integer"></xs:element>
			</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
</xs:element>


<xs:simpleType name="SecuritySal">
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="20000"></xs:minInclusive>
		<xs:maxInclusive value="150000"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="age">
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="20"></xs:minInclusive>
		<xs:maxInclusive value="60"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="floor">
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="-2"></xs:minInclusive>
		<xs:maxInclusive value="10"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>


</xs:schema>

=== renil28/SecurityXMLProgs/security.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="security.xsl"?>
<Security xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Security.xsd">
   <SecurityPersonnel>
      <Name>Renil</Name>
      <Age>22</Age>
      <Salary>20000</Salary>
      <YearsOfExperience>3</YearsOfExperience>
   </SecurityPersonnel>
   <SecurityPersonnel>
      <Name>Michael</Name>
      <Age>25</Age>
      <Salary>90000</Salary>
      <YearsOfExperience>9</YearsOfExperience>
   </SecurityPersonnel>
   <SecurityPersonnel>
      <Name>Jim</Name>
      <Age>32</Age>
      <Salary>26000</Salary>
      <YearsOfExperience>2</YearsOfExperience>
   </SecurityPersonnel>
   <SecurityPersonnel>
      <Name>Pam</Name>
      <Age>31</Age>
      <Salary>20000</Salary>
      <YearsOfExperience>2</YearsOfExperience>
   </SecurityPersonnel>
   <SecurityPersonnel>
      <Name>Steve</Name>
      <Age>22</Age>
      <Salary>20000</Salary>
      <YearsOfExperience>3</YearsOfExperience>
   </SecurityPersonnel>
   <SecurityPersonnel>
      <Name>Rithul</Name>
      <Age>52</Age>
      <Salary>35000</Salary>
      <YearsOfExperience>5</YearsOfExperience>
   </SecurityPersonnel>
   <SecurityPersonnel>
      <Name>Lull</Name>
      <Age>22</Age>
      <Salary>20000</Salary>
      <YearsOfExperience>3</YearsOfExperience>
   </SecurityPersonnel>
   <SecurityAgency>
      <AgencyName>Marks Agency</AgencyName>
      <AgencyID>25</AgencyID>
   </SecurityAgency>
   <SecurityAgency>
      <AgencyName>Stacy Agency</AgencyName>
      <AgencyID>76</AgencyID>
   </SecurityAgency>
   <SecurityEquipment>
      <EquipmentName>Armor C77</EquipmentName>
      <EquipmentType>Armor</EquipmentType>
      <EquipmentID>424</EquipmentID>
   </SecurityEquipment>
   <SecurityEquipment>
      <EquipmentName>MSF Rifle</EquipmentName>
      <EquipmentType>Weapon</EquipmentType>
      <EquipmentID>977</EquipmentID>
   </SecurityEquipment>
   <BaggageScanning>
      <BaggageName>Skybag</BaggageName>
      <BaggageID>24523</BaggageID>
   </BaggageScanning>
   <SecurityScreening>
      <GateFloorNumber>5</GateFloorNumber>
      <GateID>1363</GateID>
   </SecurityScreening>
   <CCTVCameras>
      <CameraFloor>2</CameraFloor>
      <CameraNumber>66462</CameraNumber>
   </CCTVCameras>
   <CCTVCameras>
      <CameraFloor>4</CameraFloor>
      <CameraNumber>22262</CameraNumber>
   </CCTVCameras>
   <CCTVCameras>
      <CameraFloor>5</CameraFloor>
      <CameraNumber>78862</CameraNumber>
   </CCTVCameras>
   <MallAdmin>
      <AdminName>Renil Justin</AdminName>
      <AdminID>5632323</AdminID>
   </MallAdmin>
</Security>
